#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf processor* >/dev/null 2>&1
rm -rf postProcessing* >/dev/null 2>&1
rm log.reconstructPar
rm log.foamRun
rm log.decomposePar
#------------------------------------------------------------------------------
