#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=$(getApplication)

#./Allclean

runApplication surfaceFeatures
runApplication blockMesh
runApplication snappyHexMesh -overwrite

# --- run serial ---------------------
#runApplication "$application" &

# --- run parallel -------------------
runApplication decomposePar -cellProc 
runParallel "$application" &

sleep 5
foamMonitor -l postProcessing/residuals/*/residuals.dat

runApplication reconstructPar 

#------------------------------------------------------------------------------
