#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=$(getApplication)

# Clean main case, but keep the mesh data
./Solclean 

# Run the simulation
runApplication "$application" &

# Wait for 1 sec
sleep 1

# Plot monitor data created by function objects
 foamMonitor -i 10 -r 5 -l postProcessing/residuals/*/residuals.dat &
 foamMonitor -i 10 -r 5 postProcessing/avgPres/*/surfaceFieldValue.dat 

#------------------------------------------------------------------------------
