#!/bin/sh
cd "${0%/*}" || exit 1 # Run from this directory

DIR="figs"
PYFILE="plotProbes.py"
VIDEO="elbowsnappy_ani.avi"
TMP_DIR="/tmp/${DIR}.backup"
TMP_FILE="/tmp/${PYFILE}.backup"
TMP="/tmp/${VIDEO}.backup"

# Backup erstellen
if [ -d "$KEEP_DIR" ]; then
  cp -r "$KEEP_DIR" "$TMP_DIR"
fi

if [ -f "$KEEP_FILE" ]; then
  cp "$KEEP_FILE" "$TMP_FILE"
fi

if [ -f "$VIDEO" ]; then
  cp "$VIDEO" "$TMP"
fi

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd meshing
./Meshclean
cd ..

cleanCase

# Wiederherstellen
if [ -d "$TMP_DIR" ]; then
  mv "$TMP_DIR" "$KEEP_DIR"
fi

if [ -f "$TMP_FILE" ]; then
  mv "$TMP_FILE" "$KEEP_FILE"
fi

if [ -f "$TMP" ]; then
  mv "$TMP" "$VIDEO"
fi

#--------------------------------------------------------
