#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=$(getApplication)

cd meshing
./Meshrun
cd ..
runApplication extrudeMesh
runApplication createPatch -overwrite

runApplication "$application" &

sleep 3
foamMonitor -l postProcessing/residuals/*/residuals.dat
touch post.foam

#------------------------------------------------------------------------------
