#!/bin/sh
cd "${0%/*}" || exit 1 # Run from this directory

VIDEO="elbowsnappy_ani.avi"
TMP="/tmp/${VIDEO}.backup"

# Datei sichern
if [ -f "$VIDEO" ]; then
  cp "$VIDEO" "$TMP"
fi

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd meshing
./Meshclean
cd ..

cleanCase

# Datei wiederherstellen
if [ -f "$TMP" ]; then
  mv "$TMP" "$VIDEO"
fi

#--------------------------------------------------------
