#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

VIDEO="elbowfluent_ani.avi"
TMP="/tmp/${VIDEO}.backup"
# Datei sichern
if [ -f "$VIDEO" ]; then
  cp "$VIDEO" "$TMP"
fi

rm -rf fluentInterface
cleanCase
# Datei wiederherstellen
if [ -f "$TMP" ]; then
  mv "$TMP" "$VIDEO"
fi
#------------------------------------------------------------------------------
