#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- divide stl geometry into patches according to freature angle 150 deg, 10 patches are created, just for information
# runApplication surfaceAutoPatch constant/trisurface/elbow_2D.stl constant/trisurface/elbow_2D_patch.stl 150
# -- file constant/trisurface/elbow_2D_named.stl is the resulting stl file with manually changed patch names

# -- create background mesh
runApplication blockMesh

# -- extract feature edges
runApplication surfaceFeatures

# -- create hex mesh
runApplication snappyHexMesh -overwrite
