#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# create foam file
touch post.foam
# -- create background mesh
runApplication blockMesh

# -- extract feature edges
runApplication surfaceFeatures

# -- create hex mesh
runApplication snappyHexMesh -overwrite
