#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication setFields
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar

#runApplication "$application" &

sleep 5

foamMonitor -l postProcessing/residuals/*/residuals.dat

touch post.foam
#------------------------------------------------------------------------------
