#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# close remaining foamMonitor plots
pkill -x gnuplot
pkill -x gnuplot_x11

# clean main case
cleanCase

# clean meshing case
cd meshing
cleanCase
cd ..
#------------------------------------------------------------------------------
