#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# close remaining foamMonitor plots
pkill -x gnuplot
pkill -x gnuplot_x11


# Do not clean completely, mesh is kept
# Delete time directories
foamListTimes -rm

# Delete log-file
rm log.foamRun

# Delete postprocessing data
rm -r postProcessing

#------------------------------------------------------------------------------
